### ISSUE TITLE
Todo list for fixes in future releases

### ISSUE THREAD

**Issue by e-alfred** [e-alfred/flowupload#91]
Here are some issues that should be fixed in some minor versions in the future:

* [ ] new README GIF (?)
* [ ] Security testing
* [ ] testing on Nextcloud 16
* [ ] testing on Nextcloud 17
* [ ] fix build script for Webpack/NPM
* [ ] Add warning that not all external storages are supported
